---
baseURL: "https://xsteadfastx.org/"
languageCode: "de-de"
title: "xsteadfastx"
author:
  name: "Marvin Preuss"
params:
  AuthorName: "Marvin Preuss"
  locallinks:
    - search
    - impressum
    - notes
    - all
  sociallinks:
    github: https://github.com/xsteadfastx/
    twitter: https://twitter.com/xsteadfastx
    mastodon: https://chaos.social/@xsteadfastx
    flickr: https://www.flickr.com/photos/marvinxsteadfast/
    rss: https://xsteadfastx.org/index.xml
  description: they made me do it
  images:
    - /images/xsfxmarat1000.png
theme: "xsfx"
permalinks:
  posts: "/:year/:month/:day/:slug/"
  notes: "/notes/:slug"
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: algol
outputs:
  home:
    - HTML
    - RSS
    - JSON
enableGitInfo: true
